package org.productivity.java.syslog4j;

import java.io.Serializable;

/**
* SyslogConstants provides several global constant values for several
* classes within Syslog4j.
* 
* <p>Syslog4j is licensed under the Lesser GNU Public License v2.1.  A copy
* of the LGPL license is available in the META-INF folder in all
* distributions of Syslog4j and in the base directory of the "doc" ZIP.</p>
* 
* @author &lt;syslog4j@productivity.org&gt;
* @version $Id: SyslogConstants.java,v 1.33 2011/01/11 05:11:13 cvs Exp $
*/
public interface SyslogConstants extends Serializable {
	String SYSLOG_PATH_DEFAULT = "/dev/log";
	String SYSLOG_HOST_DEFAULT = "localhost";
	int SYSLOG_PORT_DEFAULT = 514;
	int SYSLOG_BUFFER_SIZE = 1024;
	int SERVER_SOCKET_BACKLOG_DEFAULT = 50;
	
	String SYSLOG_DATEFORMAT = "MMM dd HH:mm:ss ";
	
	String STRUCTURED_DATA_NILVALUE = "-";
	String STRUCTURED_DATA_EMPTY_VALUE = "[0@0]";

	String CHAR_SET_DEFAULT = "UTF-8";

	byte[] LF = "\n".getBytes();
	byte[] CRLF = "\r\n".getBytes();
	
	byte[] TCP_DELIMITER_SEQUENCE_DEFAULT = LF;
	
	boolean THREADED_DEFAULT = true;
	long THREAD_LOOP_INTERVAL_DEFAULT = 500;

	boolean SEND_LOCAL_NAME_DEFAULT = true;
	boolean SEND_LOCAL_TIMESTAMP_DEFAULT = true;
	boolean CACHE_HOST_ADDRESS_DEFAULT = true;
	
	int MAX_MESSAGE_LENGTH_DEFAULT = 1024;
	
	boolean INCLUDE_IDENT_IN_MESSAGE_MODIFIER_DEFAULT = false;
	boolean THROW_EXCEPTION_ON_INITIALIZE_DEFAULT = true;
	boolean THROW_EXCEPTION_ON_WRITE_DEFAULT = false;
	boolean USE_STRUCTURED_DATA_DEFAULT = false;
	String STRUCTURED_DATA_APP_NAME_DEFAULT_VALUE = "unknown";
	String STRUCTURED_DATA_PROCESS_ID_DEFAULT_VALUE = STRUCTURED_DATA_NILVALUE;
	
	boolean USE_DAEMON_THREAD_DEFAULT = true;
	int THREAD_PRIORITY_DEFAULT = -1;
	
	boolean TRUNCATE_MESSAGE_DEFAULT = false;
	
	String SPLIT_MESSAGE_BEGIN_TEXT_DEFAULT = "...";
	String SPLIT_MESSAGE_END_TEXT_DEFAULT = "...";

	String SEND_LOCAL_NAME_DEFAULT_VALUE = "unknown";

	String TCP  = "tcp";
	String UDP  = "udp";
	String UNIX_SYSLOG = "unix_syslog";
	String UNIX_SOCKET = "unix_socket";
	
	boolean TCP_PERSISTENT_CONNECTION_DEFAULT = true;
	boolean TCP_SO_LINGER_DEFAULT = true;
	int TCP_SO_LINGER_SECONDS_DEFAULT = 1;
	boolean TCP_KEEP_ALIVE_DEFAULT = true;
	boolean TCP_REUSE_ADDRESS_DEFAULT = true;
	boolean TCP_SET_BUFFER_SIZE_DEFAULT = true;
	int TCP_FRESH_CONNECTION_INTERVAL_DEFAULT = -1;
	
	int TCP_MAX_ACTIVE_SOCKETS_DEFAULT = 0;
	byte TCP_MAX_ACTIVE_SOCKETS_BEHAVIOR_DEFAULT = 0;

	int FACILITY_KERN     =  0;
	int FACILITY_USER     =  1<<3;
	int FACILITY_MAIL     =  2<<3;
	int FACILITY_DAEMON   =  3<<3;
	int FACILITY_AUTH     =  4<<3;
	int FACILITY_SYSLOG   =  5<<3;

	int FACILITY_LPR      =  6<<3;
	int FACILITY_NEWS     =  7<<3;
	int FACILITY_UUCP     =  8<<3;
	int FACILITY_CRON     =  9<<3;
	int FACILITY_AUTHPRIV = 10<<3;
	int FACILITY_FTP      = 11<<3;

	int FACILITY_LOCAL0   = 16<<3;
	int FACILITY_LOCAL1   = 17<<3;
	int FACILITY_LOCAL2   = 18<<3;
	int FACILITY_LOCAL3   = 19<<3;
	int FACILITY_LOCAL4   = 20<<3;
	int FACILITY_LOCAL5   = 21<<3;
	int FACILITY_LOCAL6   = 22<<3;
	int FACILITY_LOCAL7   = 23<<3;

	int SYSLOG_FACILITY_DEFAULT = FACILITY_USER;

	int LEVEL_DEBUG = 7;
	int LEVEL_INFO = 6;
	int LEVEL_NOTICE = 5;
	int LEVEL_WARN = 4;
	int LEVEL_ERROR = 3;
	int LEVEL_CRITICAL = 2;
	int LEVEL_ALERT = 1;
	int LEVEL_EMERGENCY = 0;
	
	int OPTION_NONE = 0;
	int OPTION_LOG_CONS = 1;
	int OPTION_LOG_NDELAY = 2;
	int OPTION_LOG_NOWAIT = 4;
	int OPTION_LOG_ODELAY = 8;
	int OPTION_LOG_PERROR = 16;
	int OPTION_LOG_PID = 32;

	int SOCK_STREAM = 1;
	int SOCK_DGRAM = 2;

	short AF_UNIX = 1;
	
	int WRITE_RETRIES_DEFAULT = 2;
	int MAX_SHUTDOWN_WAIT_DEFAULT = 30000;
	long SHUTDOWN_INTERVAL = 100;
	int MAX_QUEUE_SIZE_DEFAULT = -1;
	
	long SERVER_SHUTDOWN_WAIT_DEFAULT = 500;
	
	String SYSLOG_LIBRARY_DEFAULT = "c";
	
	int SYSLOG_SOCKET_TYPE_DEFAULT = SOCK_DGRAM;
	short SYSLOG_SOCKET_FAMILY_DEFAULT = AF_UNIX;
	String SYSLOG_SOCKET_LIBRARY_DEFAULT = "c";
	int SYSLOG_SOCKET_PROTOCOL_DEFAULT = 0;
	String SYSLOG_SOCKET_PATH_DEFAULT = "/dev/log";
	
	String JNA_NATIVE_CLASS = "com.sun.jna.Native";
	
	String IDENT_SUFFIX_DEFAULT = ": ";
	
	String SYSLOG_MESSAGE_MODIFIER_PREFIX_DEFAULT = " {";
	String SYSLOG_MESSAGE_MODIFIER_SUFFIX_DEFAULT = "}";

	String SYSLOG_SEQUENTIAL_MESSAGE_MODIFIER_PREFIX_DEFAULT = " #";
	String SYSLOG_SEQUENTIAL_MESSAGE_MODIFIER_SUFFIX_DEFAULT = "";
	long SYSLOG_SEQUENTIAL_MESSAGE_MODIFIER_FIRST_NUMBER_DEFAULT = 0;
	long SYSLOG_SEQUENTIAL_MESSAGE_MODIFIER_LAST_NUMBER_DEFAULT = 9999;
	char SYSLOG_SEQUENTIAL_MESSAGE_MODIFIER_PAD_CHAR_DEFAULT = '0';
	boolean SYSLOG_SEQUENTIAL_MESSAGE_MODIFIER_USE_PADDING_DEFAULT = true;
	
	int SYSLOG_POOL_CONFIG_MAX_ACTIVE_DEFAULT = 4;
	int SYSLOG_POOL_CONFIG_MAX_IDLE_DEFAULT = 4;
	int SYSLOG_POOL_CONFIG_MAX_WAIT_DEFAULT = 1000;
	int SYSLOG_POOL_CONFIG_NUM_TESTS_PER_EVICTION_RUN_DEFAULT = 0;
	int SYSLOG_POOL_CONFIG_MIN_IDLE_DEFAULT = 4;
	int SYSLOG_POOL_CONFIG_MIN_EVICTABLE_IDLE_TIME_MILLIS_DEFAULT = 0;
	int SYSLOG_POOL_CONFIG_SOFT_MIN_EVICTABLE_IDLE_TIME_MILLIS_DEFAULT = 0;
	int SYSLOG_POOL_CONFIG_TIME_BETWEEN_EVICTION_RUNS_MILLIS_DEFAULT = 0;
	boolean SYSLOG_POOL_CONFIG_TEST_ON_BORROW_DEFAULT = false;
	boolean SYSLOG_POOL_CONFIG_TEST_ON_RETURN_DEFAULT = false;
	boolean SYSLOG_POOL_CONFIG_TEST_WHILE_IDLE_DEFAULT = false;
	String DISABLE_UNIX_PROPERTY = "syslog4j.disable.unix";
}
